### ISSUE TITLE
`seccomp=profile.json` path isn't relative to `devcontainer-feature.json` or `compose.yml`

### ISSUE THREAD

**Issue by snebjorn** [devcontainers/cli#210]
# How is a path to a seccomp profile file specificed?

This doesn't work when **seccomp.json** is in same folder as **devcontainer-feature.json**
```jsonc
// devcontainer-feature.json
{
  "securityOpt": ["seccomp=seccomp.json"]
}
```

This doesn't work **seccomp.json** is in same folder as **compose.yml**
```jsonc
// devcontainer.json
{
  "dockerComposeFile": "compose.yml",
  // rest omitted...
}
```
```yml
# compose.yml
services:
  app:
    security_opt:
      - seccomp:seccomp.json
```

seccomp accepts a path https://docs.docker.com/engine/security/seccomp/

```
$ docker run --rm \
             -it \
             --security-opt seccomp=/path/to/seccomp/profile.json \
             hello-world
```
