### ISSUE TITLE
Running in a docker-from-docker-env

### ISSUE THREAD

**Issue by max06** [devcontainers/cli#497]
Good morning,

I'm currently stuck with some issues trying to build and use a devcontainer inside of a github self-hosted runner.

The structure:
My host (ubuntu 22.04) is running docker and the self-hosted runner. My workflow contains an image to use:

```yaml
  ansible:
    runs-on: [self-hosted, docker1]
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Run Ansible Playbook
        uses: devcontainers/ci@v0.3
        with:
          imageName: max06/infra
          runCmd: ansible-playbook -i inventories/home playbooks/test.yml
```

This would run your ci-action in the defined ubuntu-container. Be aware, the runner adds the docker-socket to the container to allow docker-from-docker. (To make sure we're on the same page: This setup shares one docker daemon. A `docker ps` inside a container shows other containers running next to it)

The `docker buildx`-command executed by your tool runs just fine, probably because I'm only referring to a prebuilt image instead of building my own.
The `devcontainer up/exec`-part fails because the workspace mount specified in the command (`--mount type=bind,source=/__w/infra/infra,target=/workspaces/infra`) exists inside of the container (because the runner mounts it there), but not at the host level where the docker daemon is looking for it. 

Ideally I'd love to keep the host as clean as possible by running every job inside of a container. I'm just not really sure how to do it. I can't even tell at the moment if this is a bug or just a bad limitation...
