### ISSUE TITLE
Shell hangs from CLI, works from Visual Studio (OS X)

### ISSUE THREAD

**Issue by justinlittman** [devcontainers/cli#556]
OS X version: Darwin 22.5.0 (Ventura)
Docker version: Docker version 24.0.2, build cb74dfc
Docker compose version: Docker Compose version v2.18.1
VS Code version: 1.79.2 (Universal)
Devcontainer version: 0.42.0

devcontainer.json:
```
{
	"dockerComposeFile": "docker-compose.yml",
	"service": "devcontainer",
}
```

docker-compose.yml:
```
version: '3.6'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/ruby:3.1
    volumes:
      - ../..:/workspaces
    command: sleep infinity
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: rv-metasearch
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
```

Steps to reproduce (terminal):
1. `devcontainer up`
2. `devcontainer exec bash` (or any other shell).
3. `ls`
The terminal then hangs.

Steps to reproduce (VS Code):
1. `devcontainer up`
2. `Devcontainers: Attach to a running container ...`
3. Select the devcontainer container.
4. View > Terminal
5. `ls`
The command executes as expected.

My apologies in advance if I am misunderstanding something about how the CLI is intended to work.
