### ISSUE TITLE
Docker Compose 'build args' incompatible with mapping notation

### ISSUE THREAD

**Issue by wout-o** [devcontainers/cli#727]
**Error Encountered:**
   When starting a devcontainer I ran into the following error:
   ```bash
   docker compose --project-name my-project -f /home/user/path/to/my/docker-compose.yml -f /tmp/devcontainercli-user/docker-compose/docker-compose.devcontainer.build-1705864554615.yml config
validating /tmp/devcontainercli-user/docker-compose/docker-compose.devcontainer.build-1705864554615.yml: (root) must be a mapping
```

**Issue Details:**
The issue arises when merging two Docker Compose files with different notations for 'build args' (mapping vs. list notation). Here are the snippets from the two Docker Compose files:
- Docker Compose File 1:
  ```yaml
  services:
    laravel.test:
      build:
        args:
          WWWGROUP: '${WWWGROUP}'
  ```
- Docker Compose File 2 (generated by `devcontainers/cli`):
  ```yaml
  services:
    laravel.test:
      build:
        args:
          - BUILDKIT_INLINE_CACHE=1
          - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label
  ```

**Documentation Reference:**
According to the Docker Compose documentation, both mapping and list notations for 'build args' are valid (see [documentation](https://docs.docker.com/compose/compose-file/build/#args)).

**Code Analysis:**
The issue seems to stem from the `devcontainers/cli` package hard coding 'build args' in list notation. The relevant code snippet can be found [here](https://github.com/devcontainers/cli/blob/main/src/spec-node/dockerCompose.ts#L225).
Suggestion: The package should be able to check if the source Docker Compose file is using list or mapping notation for 'build args' and construct the override file accordingly.

**Temporary Workaround:**
A temporary workaround for this issue is to use a Docker Compose version below v2.17.0.
