### ISSUE TITLE
Build secrets from compose file ignored if features are specified

### ISSUE THREAD

**Issue by kahrpatrick** [devcontainers/cli#997]
## Problem
When specifying `features` and `dockerComposeFile` in `devcontainer.json`, build secrets specified in the referenced compose file get ignored when generating the compose override file. 

Building the container will exit with:
```bash
failed to solve: unexpected key 'env' in 'env=SOME_SECRET'
Error: Command failed: docker compose --project-name ...
```

## Steps to reproduce
1. Create a compose file with build secrets:
```yml 
---
services:
  my-service:
    image: my-image
    build:
    secrets:
      - some-secret
    ...
secrets:
  some-secret:
    file: /path/to/secret/file
...
```
2. Consume secrets in Dockerfile:
```Dockerfile
...

RUN --mount=type=secret,id=some-secret,env=SOME_SECRET ...
...
```
3. Create devcontainer configuration:
```json
{
  ...
  "dockerComposeFile": "./my-compose.yml",
  "service": "my-service",
  "features": {
    "some-feature": {}
  }
  ...
}
```
4. Build the container with: `devcontainer build --no-cache --workspace-folder .` and observe failure log.
5. Comment the "features" option in the devcontainer config file and build with success.

## Versions
`devcontainer`: 0.76.0
`docker`: 28.0.4
`docker compose`: 2.34.0
`platform`: Linux (6.6.85-2-MANJARO)
